### PR TITLE
Remove kedro-viz backend server, fetch data directly instead

### PR DESCRIPTION
**Pull request by jitu5**
In this PR We introduced use of Kedro-Viz python package with some methods `load_and_populate_data` and `get_kedro_project_json_data` from `kedro_viz.server` and `kedro_viz.api.rest.responses` from Kedro-Viz python package. 

As of now `get_kedro_project_json_data` is not yet implemented on Kedro-Viz side but once I will create PR for the same I will update here. 
https://github.com/kedro-org/kedro-viz/pull/2049

## Dev Notes
To achieve direct use of  `get_kedro_project_json_data` method and get Kedro project data we created a LSP command (`kedro.getProjectData`). This command will be called by frontend on user requested to open Viz Webview.

### CODE REVIEW

**Comment by noklam** [comment]
Note:
To test this, clone  kedro-viz and checkout feature/kedro-project-data to do editable install.

**Comment by jitu5** [comment]
> Note: To test this, clone kedro-viz and checkout feature/kedro-project-data to do editable install. @jitu5 How do I test this? Do I need a build`.vsix` as we haven't publish viz so we still need a custom version npm package?

For now, in this PR we used custom version of npm package.

**Comment by noklam** [comment]
The story is slightly more complicated. Ideally, we will pin a version of
kedro viz and vendor it with the extension.

There is question whether we need to also vendor the relevant dependencies,
viz itself is too big and we have done a lot of work to optimise this. At
the moment we do not need a viz backend server but merely using the library
code to generates some JSON.

If we choose to ask user install viz, the minimum is this should not cause
any server panic. That is, for non flowchart users they should be able to
keep their workflow without forcing to install viz.

I will open a separate issue to make sure we sort out this before release
and test it properly.

**Comment by astrojuanlu** [comment]
If we only need 2 functions from Viz, maybe another interim solution can be to duplicate them until we have a more modular backend?

**Comment by noklam** [comment]
@astrojuanlu Unfortunate those are not two small isolated util functions. Kedro Viz has it own internal structure of "Modular Pipeline", https://github.com/kedro-org/kedro-viz/blob/d171b50ba2f7f57b425d2545470c826b260758a2/package/kedro_viz/data_access/managers.py

This is all needed to generate the JSON file.

**Review by noklam — APPROVED** [review]

**Pull request merged**
