### PR TITLE
Override default_run_env instead of base_env

### PR DESCRIPTION
**Pull request by noklam**
I swear I fixed it before, but apparent I didn't.

In Kedro, the two environments work as:
- base_env: `base`
- default_run_env: `local`.

If user is changing to `prod` environment, it should be `base` + `prod` instead of `prod` + `local` (current status). 
For example, `kedro run --env=prod` is equivalent to `base_env='base', run_env='prod'`

The starting status bar now look like this:
image

# Dev Notes
- I also updated the command to indicate that `Select Kedro Run environment` instead of base
- The default is now change to `base + local`. It's not possible to change `base` environment via the extension. This is consistent to how Kedro CLI works too. It's rare one need to change base_env.
- User won't be able to choose `base`, as otherwise it will become `base + base`. We discussed briefly there may be user want to use a single environment, but we are not sure if this requirement exists, so we didn't implement this and will wait for FR instead.

### CODE REVIEW

**Review by astrojuanlu — APPROVED** [review]
So if I understood correctly, now the base environment will always be `base`, and the action/button changes the run environment, right? And the default would be `local`?

This makes more sense 👍🏼 Would the user still have the option to set the run env to `base`?

**Comment by noklam** [comment]
> So if I understood correctly, now the base environment will always be base, and the action/button changes the run environment, right? And the default would be local?

Correct, it should be the same as Kedro default.

> This makes more sense 👍🏼 Would the user still have the option to set the run env to base?

hm... good point, should we hide `base` from the options to avoid confusion? Technically you can change your "base_env" via `settings.py`, but I think that's a niche case that we can ignore from the extension.

**Comment by astrojuanlu** [comment]
I think `base + local` would be better actually. And maybe we leave the `base` option and so the text becomes just `base`?

**Comment by noklam** [comment]
> juanlu
> default should be whatever settings.py says (by default, base + local with our typical starters, right?)
> if users switch to prod, I'd expect base + prod
> switching to base is weird :sweat_smile: but maybe somebody wants to disable the env completely?? I don't know
> if we do keep the option to switch to base, then the IDE should display base (rather than base + base, that looks silly)
> I'm +1 on removing base from the env selection, to miminise confusion

For the record we agree on above in private discussion.

**Pull request merged**
