### PR TITLE
Extension env setting added

### LINKED ISSUE #14: Support environment variables (kedro run --env)
In kedro, we have the concept of "Environment" which is determined at runtime (default with `base`). The current extension always assume `base` and does not have a way to take this runtime information.

Todo:
- [ ] https://github.com/kedro-org/vscode-kedro/pull/31
- [x] #30 
- [x] #29

### PR DESCRIPTION
**Pull request by jitu5**
fix #14

Kedro Extension user now can set `base_env` from extension setting with `None` as default. 

Screenshot 2024-06-20 at 12 09 32 p m

### CODE REVIEW

**Comment by datajoely** [comment]
Great push!

Can we make this something you can set with the VS Code [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)?

**Comment by noklam** [comment]
>Can we make this something you can set with the VS Code [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)?

I think we may be able to do that, the priority then becomes:

1. "Command Palette"
2. VSCode settings
3. `KEDRO_ENV` i.e. kedro run --env prod
4. `config_loader.base_env`

**Review by noklam — APPROVED** [review]

**Comment by datajoely** [comment]
I _think_ command palette should just affect 2, but then there is also an opportunity to do this sort of thing on the bottom bar:

image

**Comment by noklam** [comment]
@datajoely Not sure about adding new UI component at this point. Before I start this I did a quick poll in the team.
image

Maybe we want to introduce a Kedro logo on the extension panel eventually.

**Pull request merged**
